max_fetch: 100
classes: ['Car', Van]
feature_size: [200, 176]

x_min: 0
x_max: 70.4

y_min: -40
y_max: 40

z_min: -3.0
z_max: 1.0

vd: 0.4     # Z
vh: 0.2     # Y
vw: 0.2     # X

T: 35

# VFE
vfe_layers: [[7,32], [32,128]]
vfe_out_channels: 128

# Sparse encoder

sparse_encoder_layers: [
  [128, 64, 3, [2,1,1], [1,1,1]],
  [64,  64, 3, [1,1,1], [0,1,1]],
  [64,  64, 3, [2,1,1], [1,1,1]],
]

# RPN

rpn_conv_block: [
  [
    [ "conv", [[128,128,3,2,1], 1]],
    [ "conv", [[128,128,3,1,1], 3]],
  ],

  [
    [ "conv", [[128,128,3,2,1], 1]],
    [ "conv", [[128,128,3,1,1], 5]],
  ],

  [
    [ "conv", [[128,256,3,2,1], 1]],
    [ "conv", [[256,256,3,1,1], 5]],
  ],
]

rpn_deconv_block: [
  [
    [ "deconv", [[128,256,1,1,0], 1]],
  ],

  [
    [ "deconv", [[128,256,2,2,0], 1]],
  ],

  [
    [ "deconv", [[256,256,4,4,0], 1]],
  ],
]

# Loss
pos_threshold: 0.6
neg_threshold: 0.45

# training

num_epochs: 160